I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/prologue.rpy", line 49, in script
    o "Hold on a second!"
Exception: Sayer 'o' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/prologue.rpy", line 49, in script
    o "Hold on a second!"
  File "/Users/enikfeirgraw/Applications/renpy-6.99.11-sdk/renpy/ast.py", line 593, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/enikfeirgraw/Applications/renpy-6.99.11-sdk/renpy/ast.py", line 509, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'o' is not defined.

Darwin-16.4.0-x86_64-i386-64bit
Ren'Py 6.99.12.2.2029
WIP 1.0
